######################################## stanza-dev-base ########################################
ARG GOLANG_VERSION=${GOLANG_VERSION:-1.24.3}
FROM golang:${GOLANG_VERSION} AS stanza-agent-dev

WORKDIR /usr/src/app

ENV GO111MODULE="on"
ENV GOOS="linux"
ENV CGO_ENABLED=0

# Copy code
COPY . /usr/src/app

# Download deps
RUN go mod download
RUN go mod verify

# Create directories for binaries and configuration
RUN mkdir -p /opt/stanza/bin

RUN go build -o /opt/stanza/bin/stzagent cmd/agent/*.go

# Entrypoint
COPY deploy/scripts/entrypoint_agent.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
